<a href="https://colab.research.google.com/github/pratapsingh23/ipl-data-analysis-pandas/blob/main/IPL_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd

df = pd.read_csv('matches.csv')

df.head(15)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,9/4/2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,9/4/2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,10/4/2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,11/4/2017,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,12/4/2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
10,11,2017,Kolkata,13/04/17,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
11,12,2017,Bangalore,14/04/17,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
12,13,2017,Rajkot,14/04/17,Rising Pune Supergiant,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,Saurashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
13,14,2017,Kolkata,15/04/17,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
14,15,2017,Delhi,15/04/17,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN

In [52]:
# Checking missing values:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

In [53]:
# filling blanks in city according to venue:

df['city'] = df['city'].fillna(df['venue'])

In [54]:
# filling blanks in winner cloumn with string "No Result

df['winner']  = df['winner'].fillna('No Result')
display(df['winner'])

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...
631    Royal Challengers Bangalore
632    Royal Challengers Bangalore
633            Sunrisers Hyderabad
634            Sunrisers Hyderabad
635            Sunrisers Hyderabad
Name: winner, Length: 636, dtype: object

In [55]:
# removing 'umpire 3' column:
df.drop(columns = ['umpire3'], inplace = True)

In [56]:
# Checking columns:

print(df.columns)

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2'],
      dtype='object')

In [57]:
# Finding Total matches:
total_matches = len(df['id'])
print("Total Matches", total_matches)

Total Matches 636

In [58]:
# How many teams played?

df['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants'],
      dtype=object)

In [59]:
#  correcting teams name :

#  Rising Pune Supergiant to Rising Pune Supergiants

change_dic = {
    'Rising Pune Supergiant':'Rising Pune Supergiants'
}

# df['team1'] = df['team1'].replace(change_dic)
# df['team2'] = df['team2'].replace(change_dic)
# df['toss_winner'] = df['toss_winner'].replace(change_dic)
# df['winner']  = df['winner'].replace(change_dic)

df = df.replace(change_dic)

df['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors'], dtype=object)

In [60]:
# which team has won most of matches?

print("Most win of each teams: \n")
df['winner'].value_counts()

Most win of each teams:

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Rising Pune Supergiants        15
Gujarat Lions                  13
Pune Warriors                  12
Kochi Tuskers Kerala            6
No Result                       3
Name: count, dtype: int64

In [61]:
# Highest number of Player of the match:

print("Top 5 POM players: ")
df['player_of_match'].value_counts().head(5).reset_index()

Top 5 POM players:

  player_of_match  count
0        CH Gayle     18
1       YK Pathan     16
2       DA Warner     15
3  AB de Villiers     15
4       RG Sharma     14

In [62]:
# Toss Winner vs Match Winner Analysis:
sum(df['toss_winner'] == df['winner'])

325

In [63]:

# Toss Decision Breakdown:

toss_break = df['toss_decision'].value_counts().reset_index()
display(toss_break)

  toss_decision  count
0         field    363
1           bat    273

In [64]:
# Most matches played in stadiums:
df['venue'].value_counts().head(5)

venue
M Chinnaswamy Stadium                        66
Eden Gardens                                 61
Feroz Shah Kotla                             60
Wankhede Stadium                             57
Rajiv Gandhi International Stadium, Uppal    49
Name: count, dtype: int64

In [65]:
# Batting first vs chasing win analysis:

# bat first:
bat_first_win = len(df[df['win_by_runs'] > 0])
bat_first_pct = (bat_first_win/total_matches)*100
print(f"Batting first wins: {bat_first_win}\nPercentage: {bat_first_pct:.2f}%\n")

# bowl first:
bowl_first_win = len(df[df['win_by_wickets'] > 0])
bowl_first_pct = (bowl_first_win/total_matches)*100
print(f"Win by chase: {bowl_first_win}\nPercnetage: {bowl_first_pct:.2f}%")

Batting first wins: 287
Percentage: 45.13%

Win by chase: 339
Percnetage: 53.30%

In [66]:
# season wise total matches:
season_wise = df.groupby('season')['id'].count().reset_index()
display(season_wise)

   season  id
0    2008  58
1    2009  57
2    2010  60
3    2011  73
4    2012  74
5    2013  76
6    2014  60
7    2015  59
8    2016  60
9    2017  59

In [67]:
#In top venue : Batting or Bowling:

chinnaswami = df[df['venue'] == 'M Chinnaswamy Stadium']
chasing_chinnaswami = len(chinnaswami[chinnaswami['win_by_wickets'] > 0])
print("Chinnaswami chasing wins: ",chasing_chinnaswami)

batting_chinnaswami = len(chinnaswami[chinnaswami['win_by_runs'] > 0])
print("Chinnaswami batting wins: ", batting_chinnaswami)

Chinnaswami chasing wins:  36
Chinnaswami batting wins:  27

In [68]:
# Final Winner of every IPL season:
final_winner = df.groupby('season')['winner'].last().reset_index()
display(final_winner)

   season                 winner
0    2008       Rajasthan Royals
1    2009        Deccan Chargers
2    2010    Chennai Super Kings
3    2011    Chennai Super Kings
4    2012  Kolkata Knight Riders
5    2013         Mumbai Indians
6    2014  Kolkata Knight Riders
7    2015         Mumbai Indians
8    2016    Sunrisers Hyderabad
9    2017         Mumbai Indians

In [69]:
# Win by biggest runs margin:

df[df['win_by_runs'] == df['win_by_runs'].max()][['season', 'team1', 'team2', 'winner', 'win_by_runs']]

    season           team1             team2          winner  win_by_runs
43    2017  Mumbai Indians  Delhi Daredevils  Mumbai Indians          146

In [70]:
# Win by biggest wickets margin:

df[df['win_by_wickets'] == df['win_by_wickets'].max()][['season', 'team1', 'team2', 'winner', 'win_by_wickets']]

,season,team1,team2,winner,win_by_wickets
2,2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,10
34,2017,Delhi Daredevils,Kings XI Punjab,Kings XI Punjab,10
71,2008,Mumbai Indians,Deccan Chargers,Deccan Chargers,10
119,2009,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,10
183,2010,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,10
298,2011,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,10
376,2012,Rajasthan Royals,Mumbai Indians,Mumbai Indians,10
390,2013,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,10
542,2015,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,10
590,2016,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,10

In [71]:
# Rivalries 1. : MI vs CSK:

# filtering:

mi_csk = df[((df['team1'] == 'Mumbai Indians') & (df['team2'] == 'Chennai Super Kings')) |
            ((df['team1'] == 'Chennai Super Kings') & (df['team2'] == 'Mumbai Indians'))]

# Head to head win count

mi_csk['winner'].value_counts().reset_index()

                winner  count
0       Mumbai Indians     12
1  Chennai Super Kings     10

In [72]:
# Rivalries 2. : RCB vs CSK:

# filtering:

rcb_csk = df[((df['team1'] == 'Chennai Super Kings') & (df['team2'] == 'Royal Challengers Bangalore')) |
            ((df['team1'] == 'Royal Challengers Bangalore') & (df['team2']) == 'Chennai Super Kings')]

# Head to head win count:

rcb_csk['winner'].value_counts().reset_index()

                        winner  count
0          Chennai Super Kings      6
1  Royal Challengers Bangalore      4